In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
# concatenation in series

In [13]:
ser1 = Series([0,1,2], index=["T", "U", "V"])
ser2 = Series([3,4], index = ["W", "x"])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

W    3
x    4
dtype: int64

In [14]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
W    3
x    4
dtype: int64

In [18]:
pd.concat([ser1, ser2], axis=1)

C:\Users\RPrince\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
W  NaN  3.0
x  NaN  4.0

In [23]:
pd.concat([ser1, ser2], keys= ["cat1", "cat2"])

cat1  T    0
      U    1
      V    2
cat2  W    3
      x    4
dtype: int64

In [24]:
dframe1 = DataFrame(np.random.randn(4,3),columns= ["x", "y", "z"])
dframe2 = DataFrame(np.random.randn(3,3),columns= ["y", "q", "x"])

In [25]:
dframe1

x         y         z
0  0.199088  0.235032  2.041480
1  1.048075  0.367773  0.363460
2 -1.841796  0.167003 -0.979226
3 -0.601410  0.961808  0.994395

In [26]:
dframe2

y         q         x
0  1.721219  0.691027  1.363183
1 -1.316654  0.265601 -0.657378
2  2.067323  0.609126  0.783613

In [27]:
pd.concat([dframe1, dframe2])

C:\Users\RPrince\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


q         x         y         z
0       NaN  0.199088  0.235032  2.041480
1       NaN  1.048075  0.367773  0.363460
2       NaN -1.841796  0.167003 -0.979226
3       NaN -0.601410  0.961808  0.994395
0  0.691027  1.363183  1.721219       NaN
1  0.265601 -0.657378 -1.316654       NaN
2  0.609126  0.783613  2.067323       NaN

In [28]:
pd.concat([dframe1, dframe2], ignore_index= True)

C:\Users\RPrince\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


q         x         y         z
0       NaN  0.199088  0.235032  2.041480
1       NaN  1.048075  0.367773  0.363460
2       NaN -1.841796  0.167003 -0.979226
3       NaN -0.601410  0.961808  0.994395
4  0.691027  1.363183  1.721219       NaN
5  0.265601 -0.657378 -1.316654       NaN
6  0.609126  0.783613  2.067323       NaN